webtalk_init -webtalk_dir D:/Shared/USN_study/HW_SW_CO_Design/VHDL/Cheating_dice/FSM/Cheating_dice_mealy/Cheating_dice_mealy.sim/sim_1/behav/xsim/xsim.dir/TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jan 15 22:34:59 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "26e5c36e-fd47-4a59-97b8-511116d264b8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d94f5ab01b58478aa81a1cba4026b17e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "100 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6188_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1334486497 -regid "" -xml D:/Shared/USN_study/HW_SW_CO_Design/VHDL/Cheating_dice/FSM/Cheating_dice_mealy/Cheating_dice_mealy.sim/sim_1/behav/xsim/xsim.dir/TB_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Shared/USN_study/HW_SW_CO_Design/VHDL/Cheating_dice/FSM/Cheating_dice_mealy/Cheating_dice_mealy.sim/sim_1/behav/xsim/xsim.dir/TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Shared/USN_study/HW_SW_CO_Design/VHDL/Cheating_dice/FSM/Cheating_dice_mealy/Cheating_dice_mealy.sim/sim_1/behav/xsim/xsim.dir/TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
