# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.cache/wt [current_project]
set_property parent.project_path D:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_repo_paths {
  d:/Shared/USN_study/Private/VHDL/vivado-library-2018.2-1/vivado-library
  d:/Shared/USN_study/vivado-library-2018.2-1
} [current_project]
update_ip_catalog
set_property ip_output_repo d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib D:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/hdl/ABC_wrapper.vhd
add_files D:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ABC.bd
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_microblaze_0_0/ABC_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_microblaze_0_0/ABC_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_microblaze_0_0/ABC_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_dlmb_v10_0/ABC_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_dlmb_v10_0/ABC_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_ilmb_v10_0/ABC_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_ilmb_v10_0/ABC_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_dlmb_bram_if_cntlr_0/ABC_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_ilmb_bram_if_cntlr_0/ABC_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_lmb_bram_0/ABC_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_mdm_1_0/ABC_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_mdm_1_0/ABC_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_clk_wiz_1_0/ABC_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_clk_wiz_1_0/ABC_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_clk_wiz_1_0/ABC_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_rst_clk_wiz_1_100M_0/ABC_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_rst_clk_wiz_1_100M_0/ABC_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_rst_clk_wiz_1_100M_0/ABC_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_axi_uartlite_0_0/ABC_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_axi_uartlite_0_0/ABC_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_axi_uartlite_0_0/ABC_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_axi_gpio_0_0/ABC_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_axi_gpio_0_0/ABC_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_axi_gpio_0_0/ABC_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_xbar_0/ABC_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_PmodGPIO_0_0/ABC_PmodGPIO_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_PmodGPIO_0_0/src/PmodGPIO_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_PmodGPIO_0_0/src/PmodGPIO_pmod_bridge_0_0/PmodGPIO_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_PmodGPIO_0_0/src/PmodGPIO_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_PmodGPIO_0_0/src/PmodGPIO_axi_gpio_0_0/PmodGPIO_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_PmodGPIO_0_0/src/PmodGPIO_axi_gpio_0_0/PmodGPIO_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_PmodGPIO_0_0/src/PmodGPIO_axi_gpio_0_0/PmodGPIO_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all D:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ABC_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ABC_wrapper -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ABC_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ABC_wrapper_utilization_synth.rpt -pb ABC_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
