# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ABC/ABC.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ABC || ORIG_REF_NAME==ABC} -quiet] -quiet

# IP: bd/ABC/ip/ABC_microblaze_0_0/ABC_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ABC_microblaze_0_0 || ORIG_REF_NAME==ABC_microblaze_0_0} -quiet] -quiet

# IP: bd/ABC/ip/ABC_dlmb_v10_0/ABC_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ABC_dlmb_v10_0 || ORIG_REF_NAME==ABC_dlmb_v10_0} -quiet] -quiet

# IP: bd/ABC/ip/ABC_ilmb_v10_0/ABC_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ABC_ilmb_v10_0 || ORIG_REF_NAME==ABC_ilmb_v10_0} -quiet] -quiet

# IP: bd/ABC/ip/ABC_dlmb_bram_if_cntlr_0/ABC_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ABC_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==ABC_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/ABC/ip/ABC_ilmb_bram_if_cntlr_0/ABC_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ABC_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==ABC_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/ABC/ip/ABC_lmb_bram_0/ABC_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ABC_lmb_bram_0 || ORIG_REF_NAME==ABC_lmb_bram_0} -quiet] -quiet

# IP: bd/ABC/ip/ABC_mdm_1_0/ABC_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ABC_mdm_1_0 || ORIG_REF_NAME==ABC_mdm_1_0} -quiet] -quiet

# IP: bd/ABC/ip/ABC_clk_wiz_1_0/ABC_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ABC_clk_wiz_1_0 || ORIG_REF_NAME==ABC_clk_wiz_1_0} -quiet] -quiet

# IP: bd/ABC/ip/ABC_rst_clk_wiz_1_100M_0/ABC_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ABC_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==ABC_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/ABC/ip/ABC_axi_uartlite_0_0/ABC_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ABC_axi_uartlite_0_0 || ORIG_REF_NAME==ABC_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/ABC/ip/ABC_axi_gpio_0_0/ABC_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ABC_axi_gpio_0_0 || ORIG_REF_NAME==ABC_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ABC/ip/ABC_PmodACL2_0_0/ABC_PmodACL2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ABC_PmodACL2_0_0 || ORIG_REF_NAME==ABC_PmodACL2_0_0} -quiet] -quiet

# IP: bd/ABC/ip/ABC_xbar_0/ABC_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ABC_xbar_0 || ORIG_REF_NAME==ABC_xbar_0} -quiet] -quiet

# IP: bd/ABC/ip/ABC_microblaze_0_axi_periph_0/ABC_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ABC_microblaze_0_axi_periph_0 || ORIG_REF_NAME==ABC_microblaze_0_axi_periph_0} -quiet] -quiet

# XDC: bd/ABC/ABC_ooc.xdc
