webtalk_init -webtalk_dir E:\\Github\\HW_SW_CO_Design\\ABC\\Group_2\\Software\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-03-16 18:53:00" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "vijikjk8t72hmr4m4tp1hl4l3j" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.425 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1552755329944" -context "sdk\\\\hardware/1552755329944"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1552755329944"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1552755329944"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1552755329944"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.3" -context "sdk\\\\hardware/1552755329944"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1552755329944"
webtalk_add_data -client sdk -key Device -value "7a35t" -context "sdk\\\\hardware/1552755329944"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1552755329944"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1552755329944"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1552755329944"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1552755329944"
webtalk_add_data -client sdk -key uid -value "1552755358862" -context "sdk\\\\bsp/1552755358862"
webtalk_add_data -client sdk -key hwid -value "1552755329944" -context "sdk\\\\bsp/1552755358862"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1552755358862"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1552755358862"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1552755358862"
webtalk_add_data -client sdk -key uid -value "1552755361409" -context "sdk\\\\application/1552755361409"
webtalk_add_data -client sdk -key hwid -value "1552755329944" -context "sdk\\\\application/1552755361409"
webtalk_add_data -client sdk -key bspid -value "1552755358862" -context "sdk\\\\application/1552755361409"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1552755361409"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1552755361409"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1552755361409"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1552755361409"
webtalk_add_data -client sdk -key LangUsed -value "CPP" -context "sdk\\\\application/1552755361409"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1552755361409"
webtalk_add_data -client sdk -key projSize -value "179.3828125" -context "sdk\\\\application/1552755361409"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1552758780964"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1552758780964"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1552758780964"
webtalk_add_data -client sdk -key DebugCount -value "21" -context "sdk\\\\bsp/1552758780964"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1552758780964"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1552758780964"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1552758780964"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1552758780964"
webtalk_transmit -clientid 3539043458 -regid "" -xml E:\\Github\\HW_SW_CO_Design\\ABC\\Group_2\\Software\\webtalk\\usage_statistics_ext_sdk.xml -html E:\\Github\\HW_SW_CO_Design\\ABC\\Group_2\\Software\\webtalk\\usage_statistics_ext_sdk.html -wdm E:\\Github\\HW_SW_CO_Design\\ABC\\Group_2\\Software\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
