# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group 2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_microblaze_0_0/ABC_microblaze_0_0.xci
# IP: The module: 'ABC_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group 2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_microblaze_0_0/ABC_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ABC_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group 2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_microblaze_0_0/ABC_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'ABC_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group 2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_microblaze_0_0/ABC_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ABC_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group 2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_microblaze_0_0/ABC_microblaze_0_0.xci
# IP: The module: 'ABC_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group 2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_microblaze_0_0/ABC_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ABC_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group 2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_microblaze_0_0/ABC_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'ABC_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group 2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_microblaze_0_0/ABC_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ABC_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
