# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_xbar_0/ABC_xbar_0.xci
# IP: The module: 'ABC_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_xbar_0/ABC_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ABC_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_xbar_0/ABC_xbar_0.xci
# IP: The module: 'ABC_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Shared/USN_study/HW_SW_CO_Design/ABC/Group_2/Software/Software.srcs/sources_1/bd/ABC/ip/ABC_xbar_0/ABC_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ABC_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
